### ISSUE TITLE
When resizing the window while visiting someone elses plant the visited plant stays visible.

### ISSUE THREAD

**Issue by ChristophGra** [jifunks/botany#31]
It appears to throw an error, and thus jump over setting the self.visited_plant to none again. This in turn results in in the interface drawing the visited plant, rather than yours for the remainder of the program running, unless you visit another garden.

https://github.com/jifunks/botany/blob/da33b69be4d947ac1b717606521495b6ea42a6fb/menu_screen.py#L719

**Comment by ChristophGra** [comment]
Reference implementation I hacked together: #32

**Comment by jifunks** [comment]
good catch, the window drawing/handling is pretty shaky in this app so there are likely 1000 other bugs around resizing the window
