### ISSUE TITLE
Use of Python 2

### ISSUE THREAD

**Issue by haydensmack** [jifunks/botany#4]
Is there a reason that this project is using python 2? Would it be better to port it to python 3?
Or are there reasons for this choice?

**Comment by jifunks** [comment]
I like Python 2 and am more familiar with its nuances. Would it be better to port? You tell me!

**Comment by fosslinux** [comment]
At this stage now, yep it would be better to port because python 2 is EOL in ~6 months.

**Comment by PaperMountainStudio** [comment]
#24
